export const REQUEST_STATUS = {
  IDLE: "IDLE",
  LOADING: "LOADING",
  SUCCESS: "SUCCESS",
  ERROR: "ERROR",
};

export const ACTIONS = {
  UPDATE_FETCHED_DATA: "UPDATE_FETCHED_DATA",
  UPDATE_REQUEST_STATUS: "UPDATE_REQUEST_STATUS",
};
